buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath libs.groovy.toml
    }
}

plugins {
    id 'java-library'
    id 'groovy'
    id 'maven-publish'
    id 'signing'
    id 'eclipse'
    id 'idea'
    alias libs.plugins.grace.doc
    alias libs.plugins.gradle.nexus.publish
    alias libs.plugins.gradle.test.retry
}

ext.'signing.keyId' = rootProject.hasProperty('signing.keyId') ? rootProject.getProperty('signing.keyId') : System.getenv('SIGNING_KEY')
ext.'signing.password' = rootProject.hasProperty('signing.password') ? rootProject.getProperty('signing.password') : System.getenv('SIGNING_PASSPHRASE')
ext.'signing.secretKeyRingFile' = rootProject.hasProperty('signing.secretKeyRingFile') ? rootProject.getProperty('signing.secretKeyRingFile') : "${System.properties['user.home']}${File.separator}.gnupg${File.separator}secring.gpg"
ext.isReleaseVersion = !projectVersion.endsWith('SNAPSHOT')

def toml = new groovy.toml.TomlSlurper()
def versions = toml.parse(rootProject.file('gradle/libs.versions.toml')).versions
def groovyVersion = versions['groovy']
def graceDataVersion = versions['grace-data']
def rxJavaVersion = versions['rxjava']
def rxJava2Version = versions['rxjava2']
def rxJava3Version = versions['rxjava3']
def springFrameworkVersion = versions['spring-framework']

version = project.projectVersion
group = 'org.graceframework.events'

repositories {
    mavenCentral()
    if (project.projectVersion.endsWith('-SNAPSHOT')) {
        maven {
            name = 'Maven Central Portal Snapshots'
            url = 'https://central.sonatype.com/repository/maven-snapshots/'

            content {
                includeGroupAndSubgroups 'org.graceframework'
            }
            mavenContent {
                snapshotsOnly()
            }
        }
    }
}

configurations {
    documentation
}

dependencies {
    documentation libs.groovy.core
    documentation libs.grace.datastore.core
    documentation libs.grace.datastore.gorm
    documentation libs.jakarta.annotation.api
    documentation libs.javaparser
    documentation libs.rxjava
    documentation libs.rxjava2
    documentation libs.rxjava3
    documentation libs.spring.beans
    documentation libs.spring.context
    documentation libs.spring.tx
}

tasks.withType(Test) {
    useJUnitPlatform()
    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
    }
    configure {
        retry {
            maxRetries = 2
            maxFailures = 20
            failOnPassedAfterRetry = true
        }
    }
}

def cleanTask = project.tasks.findByName('clean')
if (cleanTask == null) {
    task clean(type: Delete) {
        delete(buildDir)
    }
}
else {
    cleanTask.doLast {
        ant.delete(dir: 'build/docs')
    }
}

tasks.withType(Groovydoc) {
    group = 'Documentation'
    docTitle = "Grace Events Framework - ${project.version}"
    destinationDir = project.file('build/docs/manual/api')
    def files = []
    project.rootProject.subprojects
            .findAll { !it.name != 'docs' && !it.name.startsWith('examples') }
            .each { subproject ->
                if(subproject.file('src/main/groovy').exists()) {
                    files += subproject.files('src/main/groovy')
                }
                if(subproject.file('src/main/java').exists()) {
                    files += subproject.files('src/main/java')
                }
            }
    if (project.file('src/main/groovy').exists()) {
        files += project.files('src/main/groovy')
    }
    source = files
    classpath += configurations.documentation
    link('https://docs.oracle.com/en/java/javase/17/docs/api/java.base/', 'java.', 'jakarta.')
    link("https://docs.groovy-lang.org/docs/groovy-${groovyVersion}/html/gapi/", 'groovy.', 'org.codehaus.groovy.', 'org.apache.groovy.')
    link("http://reactivex.io/RxJava/javadoc/", 'rx.', 'rx.subjects.')
    link("http://reactivex.io/RxJava/2.x/javadoc/${rxJava2Version}/", 'io.reactivex.', 'io.reactivex.subjects.')
    link("http://reactivex.io/RxJava/3.x/javadoc/${rxJava3Version}/", 'io.reactivex.rxjava3.', 'io.reactivex.rxjava3.subjects.')
    link(
        "https://docs.spring.io/spring-framework/docs/${springFrameworkVersion}/javadoc-api", 
        'org.springframework.core.', 'org.springframework.context.', 'org.springframework.beans.',
        'org.springframework.dao.', 'org.springframework.transaction.', 
        'org.springframework.ui.', 'org.springframework.validation', 'org.springframework.web.'
    )
    link("https://graceframework.org/grace-data/${graceDataVersion}/api/", 'org.grails.datastore.')
}

publishGuide {
    dependsOn groovydoc
    sourceDir = project.file('src/main/docs')
}

tasks.register('docs') { task ->
    task.dependsOn groovydoc, publishGuide
}

nexusPublishing {
    repositories {
        sonatype {
            def mavenUser = System.getenv('MAVEN_CENTRAL_USER') ?: project.hasProperty('mavenCentralUsername') ? project.mavenCentralUsername : ''
            def mavenPass = System.getenv('MAVEN_CENTRAL_PASSWORD') ?: project.hasProperty('mavenCentralPassword') ? project.mavenCentralPassword : ''
            nexusUrl = uri('https://ossrh-staging-api.central.sonatype.com/service/local/')
            snapshotRepositoryUrl = uri('https://central.sonatype.com/repository/maven-snapshots/')
            username = mavenUser
            password = mavenPass
        }
    }
}
