api=../api
tags=../ref/Tags
guide=../../guide
github=https://github.com/graceframework/grace-events
sourcedir=.
sourceRepo=https://github.com/graceframework/grace-events/edit/7.1.x/src/main/docs
safe=UNSAFE
title=Grace Events Framework
subtitle=Provides various events libraries and frameworks that integrate Grace
authors=Michael Yan
copyright=Copyright &copy; 2022-2026 Michael Yan and the original authors. The content is licensed under a Creative Commons Attribution 4.0 International (CC BY SA 4.0) license.
