plugins {
    id 'grace.build.common'
}

dependencies {
    api project(':grace-events-core')
    api libs.rxjava

    testImplementation project(':grace-events-transform')
    testImplementation libs.grace.datastore.gorm.test, {
        exclude group: 'org.graceframework', module: 'grace-datastore-gorm-validation'
    }
}
