plugins {
    id 'grace.build.common'
}

dependencies {
    api project(':grace-events-core')
    api libs.jakarta.annotation.api
    compileOnly libs.grace.datastore.core, {
        transitive = false
    }
    compileOnly libs.grace.datastore.gorm, {
        transitive = false
    }

    testRuntimeOnly libs.spring.aop
    testRuntimeOnly libs.spring.expression
    testImplementation libs.grace.datastore.gorm.test, {
        exclude group: 'org.graceframework', module: 'grace-datastore-gorm-validation'
    }
}